import type {
  Word,
  Category,
  ChildProfile,
  Game,
  DailyMission,
  ProgressStats,
  OfflineMission,
} from "./types";

export const categories: Category[] = [
  { id: "1", name: "動物", icon: "🦁", color: "bg-sunny", wordCount: 24 },
  { id: "2", name: "食物", icon: "🍎", color: "bg-coral", wordCount: 18 },
  { id: "3", name: "顏色", icon: "🎨", color: "bg-sky", wordCount: 12 },
  { id: "4", name: "大自然", icon: "🌳", color: "bg-mint", wordCount: 20 },
  {
    id: "5",
    name: "交通工具",
    icon: "🚗",
    color: "bg-lavender",
    wordCount: 15,
  },
  { id: "6", name: "家庭", icon: "👨‍👩‍👧", color: "bg-coral", wordCount: 10 },
];

export const words: Word[] = [
  {
    id: "1",
    word: "大象",
    image: "/images/elephant.jpg",
    category: "動物",
    pronunciation: "daai6 zoeng6",
    definition: "一種有長長鼻子（象鼻）的巨型動物",
    example: "大象用牠的長鼻子噴水！",
    difficulty: "easy",
    mastered: false,
    exposureCount: 3,
    physicalAction: "把手臂變成長長的象鼻，前後擺動！",
    contexts: ["動物園", "森林故事", "動物圖書"],
    relatedWords: ["大", "鼻子", "灰色", "動物園"],
  },
  {
    id: "2",
    word: "蝴蝶",
    image: "/images/butterfly.jpg",
    category: "動物",
    pronunciation: "wu4 dip6",
    definition: "一種有彩色翅膀的美麗昆蟲",
    example: "蝴蝶停在花朵上。",
    difficulty: "medium",
    mastered: true,
    exposureCount: 8,
    physicalAction: "張開雙臂像翅膀一樣，在房間裡飛來飛去！",
    contexts: ["花園", "花朵上", "春天"],
    relatedWords: ["翅膀", "飛", "彩色", "花"],
  },
  {
    id: "3",
    word: "蘋果",
    image: "/images/apple.jpg",
    category: "食物",
    pronunciation: "ping4 gwo2",
    definition: "一種圓形、紅色或綠色、口感爽脆的水果",
    example: "我吃了一個蘋果當點心。",
    difficulty: "easy",
    mastered: true,
    exposureCount: 12,
    physicalAction: "假裝摘一個蘋果，然後大口咬下去，發出清脆的聲音！",
    contexts: ["茶點時間", "超級市場", "飯盒"],
    relatedWords: ["水果", "紅色", "爽脆", "甜"],
  },
  {
    id: "4",
    word: "彩虹",
    image: "/images/rainbow.jpg",
    category: "大自然",
    pronunciation: "coi2 hung4",
    definition: "雨後天空中出現的彩色條紋",
    example: "看！天空中有一道彩虹！",
    difficulty: "easy",
    mastered: false,
    exposureCount: 5,
    physicalAction: "用雙手在空中畫一個大大的拱形！",
    contexts: ["雨後", "天空", "下雨天"],
    relatedWords: ["顏色", "天空", "雨", "美麗"],
  },
  {
    id: "5",
    word: "長頸鹿",
    image: "/images/giraffe.jpg",
    category: "動物",
    pronunciation: "coeng4 geng2 luk6",
    definition: "一種脖子很長、有斑點的高大動物",
    example: "長頸鹿吃高樹上的葉子。",
    difficulty: "medium",
    mastered: false,
    exposureCount: 2,
    physicalAction: "把脖子伸得長長的，假裝去吃高處的葉子！",
    contexts: ["動物園", "非洲", "吃樹葉"],
    relatedWords: ["高", "脖子", "斑點", "葉子"],
  },
  {
    id: "6",
    word: "士多啤梨",
    image: "/images/strawberry.jpg",
    category: "食物",
    pronunciation: "si6 do1 be1 lei2",
    definition: "一種紅色的小水果，表面有細小的種子",
    example: "士多啤梨又甜又好味！",
    difficulty: "medium",
    mastered: false,
    exposureCount: 4,
    physicalAction: "假裝摘一顆小小的士多啤梨放進嘴裡！",
    contexts: ["甜品", "果昔", "農場"],
    relatedWords: ["水果", "紅色", "甜", "種子"],
  },
];

export const todaysWords: Word[] = words.slice(0, 3);

export const childProfile: ChildProfile = {
  id: "1",
  name: "Emma",
  avatar: "👧",
  age: 4,
  level: 5,
  xp: 350,
  wordsLearned: 47,
  currentStreak: 7,
  interests: ["動物", "大自然"],
  dailyGoal: 5,
  todayProgress: 3,
  learningStyle: "kinesthetic",
  attentionSpan: 15,
  preferredTimeOfDay: "morning",
};

export const games: Game[] = [
  {
    id: "1",
    name: "配對遊戲",
    description: "將圖片配對",
    icon: "🎯",
    color: "bg-coral",
    type: "matching",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "2",
    name: "找找看",
    description: "尋找隱藏物品",
    icon: "🔍",
    color: "bg-sky",
    type: "ispy",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: true,
  },
  {
    id: "3",
    name: "跟我讀",
    description: "練習發音",
    icon: "🎤",
    color: "bg-mint",
    type: "pronunciation",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "4",
    name: "做動作",
    description: "用身體動作表達詞彙",
    icon: "🕺",
    color: "bg-sunny",
    type: "charades",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: true,
  },
  {
    id: "5",
    name: "動感學習",
    description: "邊做動作邊學習",
    icon: "🤸",
    color: "bg-lavender",
    type: "actions",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "6",
    name: "搜羅詞彙",
    description: "在周圍尋找實物",
    icon: "🏃",
    color: "bg-coral",
    type: "scavenger",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: true,
  },
];

export const dailyMissions: DailyMission[] = [
  {
    id: "1",
    title: "早餐對話",
    description: "早餐時使用這些詞彙",
    targetWord: "蘋果",
    completed: true,
    context: "問問小朋友：「蘋果是什麼顏色的？」和「它是爽脆的還是軟綿綿的？」",
  },
  {
    id: "2",
    title: "大自然漫步",
    description: "在戶外尋找這些東西",
    targetWord: "蝴蝶",
    completed: false,
    context: "尋找蝴蝶，並談論牠們的顏色和飛行方式。",
  },
  {
    id: "3",
    title: "故事時間",
    description: "一起閱讀故事",
    targetWord: "大象",
    completed: false,
    context: "模仿大象走路和使用鼻子的樣子！",
  },
];

export const progressStats: ProgressStats = {
  totalWords: 99,
  masteredWords: 47,
  weeklyProgress: [3, 5, 4, 6, 5, 4, 3],
  streakDays: 7,
  categoryProgress: [
    { category: "動物", progress: 75 },
    { category: "食物", progress: 60 },
    { category: "顏色", progress: 90 },
    { category: "大自然", progress: 45 },
    { category: "交通工具", progress: 30 },
  ],
  averageExposuresPerWord: 6.2,
  activeVocabulary: 28,
  passiveVocabulary: 71,
  multiSensoryEngagement: 75,
};

export const offlineMissions: OfflineMission[] = [
  {
    id: "m1",
    title: "尋找紅色蘋果",
    description: "在午餐或茶點時間，引導小朋友辨認紅色水果。",
    context: "mealtime",
    targetWords: ["蘋果", "紅色", "甜"],
    completed: false,
    conversationPrompts: [
      "你看！這是什麼顏色的？(指著蘋果)",
      "蘋果好唔好食呀？係咪好甜？",
      "我們可以數一數碟上面有幾多塊蘋果嗎？",
    ],
  },
  {
    id: "m2",
    title: "晚安月亮",
    description: "睡前望出窗外，尋找月亮並說晚安。",
    context: "bedtime",
    targetWords: ["月亮", "睡覺", "黑"],
    completed: true,
    conversationPrompts: [
      "嘩！你看天空上面有個好光的月亮！",
      "月亮要在什麼時候才出來？",
      "我們要跟月亮說什麼？晚安！",
    ],
  },
  {
    id: "m3",
    title: "超級市場大搜查",
    description: "購物時，讓小朋友幫忙尋找牛奶。",
    context: "shopping",
    targetWords: ["牛奶", "白色", "凍"],
    completed: false,
    conversationPrompts: [
      "這是牛奶嗎？",
      "牛奶是什麼顏色的？",
      "摸摸看，這瓶牛奶是熱的還是凍的？",
    ],
  },
  {
    id: "m4",
    title: "公園顏色捉迷藏",
    description: "在公園找出綠色的東西。",
    context: "outdoor",
    targetWords: ["樹", "草", "綠色"],
    completed: false,
    conversationPrompts: [
      "我們來找找看，哪裡有綠色的東西？",
      "大樹是什麼顏色的？",
      "我們可以踩在草地上嗎？",
    ],
  },
  {
    id: "m5",
    title: "早餐對話挑戰",
    description: "在早餐時間談論食物的顏色和味道。",
    context: "mealtime",
    targetWords: ["多士", "黃色", "脆"],
    completed: false,
    conversationPrompts: [
      "你的多士是什麼顏色的？",
      "咬一口試試，是不是很脆？",
      "你還想吃什麼？",
    ],
  },
  {
    id: "m6",
    title: "玩具收拾時間",
    description: "在收拾玩具時，練習分類和顏色。",
    context: "playtime",
    targetWords: ["車", "紅色", "箱子"],
    completed: false,
    conversationPrompts: [
      "這輛車是什麼顏色的？",
      "我們可以把紅色的玩具放進箱子裡嗎？",
      "謝謝你幫忙收拾！",
    ],
  },
];
