import type {
  Word,
  Category,
  ChildProfile,
  Story,
  Game,
  DailyMission,
  ProgressStats,
  OfflineMission,
} from "./types";

export const categories: Category[] = [
  { id: "1", name: "Animals", icon: "🦁", color: "bg-sunny", wordCount: 24 },
  { id: "2", name: "Food", icon: "🍎", color: "bg-coral", wordCount: 18 },
  { id: "3", name: "Colors", icon: "🎨", color: "bg-sky", wordCount: 12 },
  { id: "4", name: "Nature", icon: "🌳", color: "bg-mint", wordCount: 20 },
  {
    id: "5",
    name: "Vehicles",
    icon: "🚗",
    color: "bg-lavender",
    wordCount: 15,
  },
  { id: "6", name: "Family", icon: "👨‍👩‍👧", color: "bg-coral", wordCount: 10 },
];

export const words: Word[] = [
  {
    id: "1",
    word: "Elephant",
    image: "/images/elephant.jpg",
    category: "Animals",
    pronunciation: "EL-uh-funt",
    definition: "A very big animal with a long nose called a trunk",
    example: "The elephant sprays water with its trunk!",
    difficulty: "easy",
    mastered: false,
    exposureCount: 3,
    physicalAction:
      "Make your arm into a long trunk and swing it back and forth!",
    contexts: ["At the zoo", "In jungle stories", "In animal books"],
    relatedWords: ["big", "trunk", "gray", "zoo"],
  },
  {
    id: "2",
    word: "Butterfly",
    image: "/images/butterfly.jpg",
    category: "Animals",
    pronunciation: "BUH-ter-fly",
    definition: "A pretty insect with colorful wings",
    example: "The butterfly landed on the flower.",
    difficulty: "medium",
    mastered: true,
    exposureCount: 8,
    physicalAction: "Spread your arms like wings and flutter around the room!",
    contexts: ["In the garden", "On flowers", "In spring time"],
    relatedWords: ["wings", "fly", "colorful", "flower"],
  },
  {
    id: "3",
    word: "Apple",
    image: "/images/apple.jpg",
    category: "Food",
    pronunciation: "AP-uhl",
    definition: "A round red or green fruit that is crunchy",
    example: "I eat an apple for my snack.",
    difficulty: "easy",
    mastered: true,
    exposureCount: 12,
    physicalAction: "Pretend to pick an apple and take a big crunchy bite!",
    contexts: ["At snack time", "At the store", "In lunch box"],
    relatedWords: ["fruit", "red", "crunchy", "sweet"],
  },
  {
    id: "4",
    word: "Rainbow",
    image: "/images/rainbow.jpg",
    category: "Nature",
    pronunciation: "RAIN-boh",
    definition: "Colorful stripes in the sky after rain",
    example: "Look! There is a rainbow in the sky!",
    difficulty: "easy",
    mastered: false,
    exposureCount: 5,
    physicalAction: "Draw a big arch in the air with both arms!",
    contexts: ["After rain", "In the sky", "On rainy days"],
    relatedWords: ["colors", "sky", "rain", "beautiful"],
  },
  {
    id: "5",
    word: "Giraffe",
    image: "/images/giraffe.jpg",
    category: "Animals",
    pronunciation: "juh-RAF",
    definition: "A tall animal with a very long neck and spots",
    example: "The giraffe eats leaves from tall trees.",
    difficulty: "medium",
    mastered: false,
    exposureCount: 2,
    physicalAction: "Stretch your neck up high and reach for pretend leaves!",
    contexts: ["At the zoo", "In Africa", "Eating from trees"],
    relatedWords: ["tall", "neck", "spots", "leaves"],
  },
  {
    id: "6",
    word: "Strawberry",
    image: "/images/strawberry.jpg",
    category: "Food",
    pronunciation: "STRAW-beh-ree",
    definition: "A small red fruit with tiny seeds",
    example: "Strawberries are sweet and yummy!",
    difficulty: "medium",
    mastered: false,
    exposureCount: 4,
    physicalAction: "Pretend to pick a tiny berry and pop it in your mouth!",
    contexts: ["For dessert", "In smoothies", "At the farm"],
    relatedWords: ["fruit", "red", "sweet", "seeds"],
  },
];

export const todaysWords: Word[] = words.slice(0, 3);

export const childProfile: ChildProfile = {
  id: "1",
  name: "Emma",
  avatar: "👧",
  age: 4,
  level: 5,
  xp: 350,
  wordsLearned: 47,
  currentStreak: 7,
  interests: ["Animals", "Nature"],
  dailyGoal: 5,
  todayProgress: 3,
  learningStyle: "kinesthetic",
  attentionSpan: 15,
  preferredTimeOfDay: "morning",
};

export const stories: Story[] = [
  {
    id: "1",
    title: "The Hungry Caterpillar",
    cover: "/images/caterpillar-story.jpg",
    words: words.filter(
      (w) => w.category === "Animals" || w.category === "Food",
    ),
    duration: "5 min",
    completed: false,
    repeatCount: 0,
    pages: [
      {
        id: "1-1",
        text: "Once upon a time, there was a tiny caterpillar. She was very, very hungry!",
        highlightedWords: ["caterpillar", "hungry"],
        emoji: "🐛",
        dialogicPrompts: [
          {
            id: "p1-1",
            type: "prediction",
            question: "What do you think the caterpillar wants to do?",
            targetWords: ["eat", "hungry"],
          },
        ],
        physicalAction: "Wiggle like a caterpillar!",
      },
      {
        id: "1-2",
        text: "On Monday, she ate one red apple. Crunch, crunch! It was so yummy.",
        highlightedWords: ["apple", "red"],
        emoji: "🍎",
        dialogicPrompts: [
          {
            id: "p1-2",
            type: "open-ended",
            question: "What does an apple taste like? Is it sweet or sour?",
            targetWords: ["apple", "sweet", "crunchy"],
          },
        ],
        physicalAction: "Pretend to take a big crunchy bite!",
      },
      {
        id: "1-3",
        text: "On Tuesday, she ate two sweet strawberries. They were her favorite!",
        highlightedWords: ["strawberries", "sweet"],
        emoji: "🍓",
        dialogicPrompts: [
          {
            id: "p1-3",
            type: "connection",
            question: "Have you ever eaten strawberries? Did you like them?",
            targetWords: ["strawberries", "favorite"],
          },
        ],
      },
      {
        id: "1-4",
        text: "After eating so much, she felt sleepy. She made a cozy cocoon and went to sleep.",
        highlightedWords: ["sleepy", "cocoon"],
        emoji: "🛏️",
        physicalAction: "Curl up in a ball like a cocoon!",
      },
      {
        id: "1-5",
        text: "When she woke up, she was a beautiful butterfly! She could fly high in the sky.",
        highlightedWords: ["butterfly", "fly"],
        emoji: "🦋",
        dialogicPrompts: [
          {
            id: "p1-5",
            type: "recall",
            question: "What did the caterpillar eat first? Can you remember?",
            targetWords: ["apple"],
          },
        ],
        physicalAction: "Spread your arms and fly around like a butterfly!",
      },
    ],
    comprehensionQuestions: [
      {
        id: "c1",
        type: "recall",
        question: "What did the caterpillar turn into?",
        targetWords: ["butterfly"],
      },
      {
        id: "c2",
        type: "open-ended",
        question: "What was your favorite part of the story?",
        targetWords: [],
      },
    ],
  },
  {
    id: "2",
    title: "Colors All Around",
    cover: "/images/colors-story.jpg",
    words: words.filter(
      (w) => w.category === "Colors" || w.category === "Nature",
    ),
    duration: "4 min",
    completed: true,
    repeatCount: 2,
    pages: [
      {
        id: "2-1",
        text: "Look outside! The sky is blue. Big fluffy clouds float by.",
        highlightedWords: ["blue", "sky", "clouds"],
        emoji: "☁️",
      },
      {
        id: "2-2",
        text: "The grass is green. Little flowers grow in the garden.",
        highlightedWords: ["green", "grass", "flowers"],
        emoji: "🌱",
      },
      {
        id: "2-3",
        text: "The sun is yellow and bright. It makes everything warm and happy.",
        highlightedWords: ["yellow", "sun", "bright"],
        emoji: "☀️",
      },
      {
        id: "2-4",
        text: "After the rain, look up! A beautiful rainbow appears in the sky!",
        highlightedWords: ["rainbow", "rain", "beautiful"],
        emoji: "🌈",
      },
    ],
  },
  {
    id: "3",
    title: "Animal Friends",
    cover: "/images/animals-story.jpg",
    words: words.filter((w) => w.category === "Animals"),
    duration: "6 min",
    completed: false,
    pages: [
      {
        id: "3-1",
        text: "In the jungle, there lived a big elephant. He had a very long trunk!",
        highlightedWords: ["elephant", "jungle", "trunk"],
        emoji: "🐘",
      },
      {
        id: "3-2",
        text: "His friend was a tall giraffe. She could eat leaves from the tallest trees.",
        highlightedWords: ["giraffe", "tall", "leaves"],
        emoji: "🦒",
      },
      {
        id: "3-3",
        text: "A playful monkey swung from tree to tree. He loved to eat bananas!",
        highlightedWords: ["monkey", "bananas", "playful"],
        emoji: "🐒",
      },
      {
        id: "3-4",
        text: "A colorful parrot sang a happy song. All the animals danced together!",
        highlightedWords: ["parrot", "sang", "danced"],
        emoji: "🦜",
      },
      {
        id: "3-5",
        text: "The animals were the best of friends. They played together every day. The End!",
        highlightedWords: ["friends", "played", "together"],
        emoji: "❤️",
      },
    ],
  },
];

export const games: Game[] = [
  {
    id: "1",
    name: "Word Match",
    description: "Match pictures to words",
    icon: "🎯",
    color: "bg-coral",
    type: "matching",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "2",
    name: "I Spy",
    description: "Find hidden objects",
    icon: "🔍",
    color: "bg-sky",
    type: "ispy",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: true,
  },
  {
    id: "3",
    name: "Say It!",
    description: "Practice saying words",
    icon: "🎤",
    color: "bg-mint",
    type: "pronunciation",
    physicalActivity: false,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "4",
    name: "Act It Out!",
    description: "Show the word with your body",
    icon: "🕺",
    color: "bg-sunny",
    type: "charades",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: true,
  },
  {
    id: "5",
    name: "Move & Learn",
    description: "Do actions for each word",
    icon: "🤸",
    color: "bg-lavender",
    type: "actions",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: false,
  },
  {
    id: "6",
    name: "Word Hunt",
    description: "Find real objects around you",
    icon: "🏃",
    color: "bg-coral",
    type: "scavenger",
    physicalActivity: true,
    multiSensory: true,
    parentParticipation: true,
  },
];

export const dailyMissions: DailyMission[] = [
  {
    id: "1",
    title: "Breakfast Talk",
    description: "Use these words during breakfast",
    targetWord: "Apple",
    completed: true,
    context:
      'Ask your child: "What color is the apple?" and "Is it crunchy or soft?"',
  },
  {
    id: "2",
    title: "Nature Walk",
    description: "Find these things outside",
    targetWord: "Butterfly",
    completed: false,
    context:
      "Look for butterflies and talk about their colors and how they fly.",
  },
  {
    id: "3",
    title: "Story Time",
    description: "Read a story together",
    targetWord: "Elephant",
    completed: false,
    context: "Act out how an elephant walks and uses its trunk!",
  },
];

export const progressStats: ProgressStats = {
  totalWords: 99,
  masteredWords: 47,
  weeklyProgress: [3, 5, 4, 6, 5, 4, 3],
  streakDays: 7,
  categoryProgress: [
    { category: "Animals", progress: 75 },
    { category: "Food", progress: 60 },
    { category: "Colors", progress: 90 },
    { category: "Nature", progress: 45 },
    { category: "Vehicles", progress: 30 },
  ],
  averageExposuresPerWord: 6.2,
  activeVocabulary: 28,
  passiveVocabulary: 71,
  multiSensoryEngagement: 75,
};

export const offlineMissions: OfflineMission[] = [
  {
    id: "om1",
    title: "Breakfast Conversation",
    description: "Talk about food during breakfast",
    targetWords: ["apple", "strawberry", "sweet", "crunchy"],
    context: "mealtime",
    completed: true,
    conversationPrompts: [
      "What color is this fruit?",
      "Is it crunchy or soft?",
      "Can you name other fruits you like?",
      "What does it taste like?",
    ],
  },
  {
    id: "om2",
    title: "Animal Sounds Walk",
    description: "Find and talk about animals during a walk",
    targetWords: ["butterfly", "bird", "dog", "cat"],
    context: "outdoor",
    completed: false,
    conversationPrompts: [
      "Can you see any animals?",
      "What sound does that animal make?",
      "How does it move?",
      "What is it doing right now?",
    ],
  },
  {
    id: "om3",
    title: "Bedtime Story Time",
    description: "Read together and act out parts",
    targetWords: ["elephant", "giraffe", "sleepy", "dream"],
    context: "bedtime",
    completed: false,
    conversationPrompts: [
      "Can you show me how an elephant walks?",
      "What do you think happens next?",
      "Which character do you like best?",
      "Can you tell me about your favorite part?",
    ],
  },
  {
    id: "om4",
    title: "Color Hunt at Home",
    description: "Find objects of different colors",
    targetWords: ["red", "blue", "green", "yellow"],
    context: "playtime",
    completed: false,
    conversationPrompts: [
      "Can you find something red?",
      "What else is blue in our house?",
      "Which is your favorite color?",
      "Can you make a rainbow with your toys?",
    ],
  },
  {
    id: "om5",
    title: "Grocery Store Adventure",
    description: "Name items while shopping",
    targetWords: ["apple", "banana", "milk", "bread"],
    context: "shopping",
    completed: false,
    conversationPrompts: [
      "Can you help me find the apples?",
      "What color are the bananas?",
      "How many should we get?",
      "What will we make with these?",
    ],
  },
  {
    id: "om6",
    title: "Nature Explorer",
    description: "Discover nature together",
    targetWords: ["tree", "flower", "grass", "sky"],
    context: "outdoor",
    completed: false,
    conversationPrompts: [
      "What do you see in the sky?",
      "Can you touch the grass? How does it feel?",
      "What colors are the flowers?",
      "How tall is that tree?",
    ],
  },
];
