// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/child/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/child">> = Specific
  const handler = {} as typeof import("../../../../../../app/child/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/create-child/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-child">> = Specific
  const handler = {} as typeof import("../../../../../../app/create-child/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/parent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent">> = Specific
  const handler = {} as typeof import("../../../../../../app/parent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/test-images/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-images">> = Specific
  const handler = {} as typeof import("../../../../../../app/test-images/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/test-speech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-speech">> = Specific
  const handler = {} as typeof import("../../../../../../app/test-speech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/test-story-loader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-story-loader">> = Specific
  const handler = {} as typeof import("../../../../../../app/test-story-loader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/external-word-learned/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-word-learned">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/external-word-learned/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/generate-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-image">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/generate-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[...path]">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/vocabulary/external/word-learned/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vocabulary/external/word-learned">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/vocabulary/external/word-learned/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/api/wordlearned/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wordlearned">> = Specific
  const handler = {} as typeof import("../../../../../../app/api/wordlearned/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../../../../../app/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../../../app/child/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/child">> = Specific
  const handler = {} as typeof import("../../../../../../app/child/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../app/parent/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/parent">> = Specific
  const handler = {} as typeof import("../../../../../../app/parent/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
